# This is a basic workflow to help you get started with Actions

name: Deploy on new content dispatch

# Controls when the action will run. Triggers the workflow on push or pull request
# Events but only for the master branch
on:
  repository_dispatch:
    types: [merge-content]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
    mergeContent:
      # The type of runner that the job will run on
      runs-on: ubuntu-latest
      
      # Steps represent a sequence of tasks that will be executed as part of the job
      steps:
          - uses: actions/checkout@v2
          - name: Clone/Checkout submodules
            uses: actions/checkout@v2
            with:
              token: ${{ secrets.DISPATCH_HOOK_TOKEN }}
              submodules: true
              
          - name: Update submodules content
            run: git submodule update --remote --recursive
          - name: Pull the content
            run: git pull
          - name: Update submodules index
            uses: stefanzweifel/git-auto-commit-action@v4.8.0
            with:
              commit_message: GHA - New post! Submodule ref updated.
              commit_user_name: My GitHub Actions Bot
